include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-fakehttp
PKG_RELEASE:=5

PKG_MAINTAINER:=FakeHTTP LuCI feed
PKG_LICENSE:=GPL-3.0-or-later

LUCI_TITLE:=LuCI support for FakeHTTP
LUCI_DEPENDS:=+fakehttp
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
